#!/usr/bin/python
import os, sys
def main():
	script = "sudo debian-user '/home/user/lib/canon_download --interactive"
	script += " --destination /home/user/MyDocs/Canon-EOS400D"
	script += " " + " ".join(sys.argv[1:])
	script += "'"
	os.close(0)
	os.open("/dev/null", os.O_RDONLY)
	if os.fork() != 0:
		sys.exit(0)
	cmd = "run-standalone.sh"
	os.execlp(cmd, cmd, "osso-xterm", "-e", script)
if __name__ == "__main__":
	main()
