#!/usr/bin/python
# canon_download_term, Copyright (C) 2012 Stuart Pook (http://www.pook.it/)
# This program is run in a xterm by a udev run when the camera ia plugged in to
# a USB port.

# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT ANY
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os, sys
def main():
	if os.fork() != 0:
		sys.exit(0)
	script = "sudo debian-user '/home/user/lib/canon_download --interactive"
	script += " --destination /home/user/MyDocs/Canon-EOS400D/raw"
	script += " " + " ".join(sys.argv[1:])
	script += "'"
	os.close(0)
	os.open("/dev/null", os.O_RDONLY)
	cmd = "run-standalone.sh"
	os.execlp(cmd, cmd, "osso-xterm", "-e", script)
if __name__ == "__main__":
	main()
